source "azure-arm" "autogenerated_1" {
  azure_tags = {
    dept = "Engineering"
    task = "Image deployment"
  }

  client_id                         = "0da70c7d-213b-4fd9-8e97-e414e5fa6190"
  client_secret                     = "YWUV-SzoyrkEJ02Ve1B93lbShs6eqlVu~H"
  image_offer                       = "0001-com-ubuntu-server-impish"
  image_publisher                   = "Canonical"
  image_sku                         = "21_10-gen2"
  location                          = "UK South"
  managed_image_name                = "myPackerImage"
  managed_image_resource_group_name = "myPackerImages"
  os_type                           = "Linux"
  subscription_id                   = "d0f6eb41-3e86-48da-bc57-893eab20796f"
  tenant_id                         = "88ef261e-b19b-4d71-9afd-cdac31a6dcda"
  vm_size                           = "Standard_B1ms"
}

build {
  sources = ["source.azure-arm.autogenerated_1"]

  provisioner "shell" {
    execute_command = "chmod +x {{ .Path }}; {{ .Vars }} sudo -E sh '{{ .Path }}'"
    inline          = ["apt-get update", "apt-get upgrade -y", "apt-get -y install nginx", "/usr/sbin/waagent -force -deprovision+user && export HISTSIZE=0 && sync"]
    inline_shebang  = "/bin/sh -x"
  }
}
